I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 502, in script
    $ has_malware = flag_1_6A1==1
  File "game/script.rpy", line 502, in <module>
    $ has_malware = flag_1_6A1==1
NameError: name 'flag_1_6A1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 502, in script
    $ has_malware = flag_1_6A1==1
  File "C:\Users\match\Documents\SHS_JeuVideo\SHS_Cybersecurity_game\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\match\Documents\SHS_JeuVideo\SHS_Cybersecurity_game\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 502, in <module>
    $ has_malware = flag_1_6A1==1
NameError: name 'flag_1_6A1' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Please do not hack me 1.0
Mon Apr 27 23:52:31 2020
