I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 879, in script
    A "Hé Bob ! Oui super, et toi ?"
Exception: Sayer 'A' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 879, in script
    A "Hé Bob ! Oui super, et toi ?"
  File "C:\Users\yanni\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\yanni\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'A' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Please do not hack me 1.0
Tue May 12 17:49:35 2020
